content-only:
  groupname: content-only
  access:
    site: {  }
    admin:
      super: 'false'
      login: 'true'
      cache: 'false'
      configuration: 'false'
      configuration_system: 'false'
      configuration_site: 'true'
      configuration_media: 'false'
      configuration_info: 'true'
      settings: 'true'
      pages: 'true'
      maintenance: 'true'
      statistics: 'true'
      plugins: 'false'
      themes: 'false'
      users: 'false'
    admin-addon-user-manager:
      users: 'false'
      groups: 'false'
      users_expert: 'false'
