title: Russlanddeutsch
default_lang: de
author:
  name: 'no Author'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: '#russlanddeutsch'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
